from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any


# This dataclass represents the normalised decision schema described in Section 4.4.
# Every incoming AI decision (no matter how messy) should eventually be mapped
# into this structure before we score it against any governance framework.
@dataclass
class Decision:
    # Unique reference generated by GovGuard (can be None for now and filled later)
    decision_id: Optional[str] = None

    # Name of the client AI system making the decision (e.g. "Benefits Eligibility Checker v2")
    system_name: str = ""

    # Name of the deploying organisation or department (e.g. "DWP", "Manchester Council")
    department: Optional[str] = None

    # ISO 8601 timestamp string (e.g. "2026-03-05T09:32:00Z")
    timestamp: Optional[str] = None

    # Category of decision (eligibility, screening, triage, approval, flagging)
    decision_type: str = ""

    # Who or what is affected: "individual", "organisation", or "system"
    affected_party: str = ""

    # What was decided (e.g. "denied", "approved", "candidate_rejected")
    outcome: str = ""

    # Model certainty between 0.0 and 1.0
    confidence_score: float = 0.0

    # Name and version of the model used (e.g. "mistral-7b-v2.1")
    model_used: Optional[str] = None

    # List of data sources involved in the decision (e.g. ["HMRC feed", "UC database"])
    data_sources: List[str] = field(default_factory=list)

    # Was a human reviewer meaningfully involved in the decision?
    human_in_loop: bool = False

    # Was an explanation given to the affected individual?
    explanation_provided: bool = False

    # Is there a way for the individual to challenge the decision?
    appeal_pathway: bool = False

    # Is the decision logged so it can be audited later?
    audit_trail: bool = False

    # Optional: did the decision use sensitive data? (not explicit in 4.4 but used in 5.2)
    sensitive_data_used: bool = False

    # Optional: is the model version explicitly recorded?
    model_version_recorded: bool = True

    # Optional: are data_sources complete and well documented?
    data_sources_complete: bool = True


# This function implements the UK AI Playbook risk scoring logic from Section 5.2.
# It takes a single Decision object and returns the risk score, risk level, action,
# and a list of violation codes, all focused on the UK AI Playbook framework.
def score_uk_ai_playbook(decision: Decision) -> Dict[str, Any]:
    # We start from a clean score and add penalty weights for each violation.
    risk_score = 0.0
    violations: List[str] = []

    # ---- CRITICAL violations (0.25 each) ----
    # human_in_loop = false  → automation without oversight
    if not decision.human_in_loop:
        risk_score += 0.25
        violations.append("human_oversight_missing")

    # appeal_pathway = false → no right to challenge
    if not decision.appeal_pathway:
        risk_score += 0.25
        violations.append("no_appeal_pathway")

    # ---- HIGH violations (0.15 each) ----
    # explanation_provided = false → transparency failure
    if not decision.explanation_provided:
        risk_score += 0.15
        violations.append("no_explanation_provided")

    # audit_trail = false → no accountability record
    if not decision.audit_trail:
        risk_score += 0.15
        violations.append("no_audit_trail")

    # ---- MEDIUM violations (0.10 each) ----
    # confidence_score > 0.95 → over-reliance on automation
    if decision.confidence_score > 0.95:
        risk_score += 0.10
        violations.append("overconfident_automation")

    # sensitive_data_used = true → privacy risk flag
    if decision.sensitive_data_used:
        risk_score += 0.10
        violations.append("sensitive_data_risk")

    # ---- LOW violations (0.05 each) ----
    # model_version not recorded → traceability gap
    if not decision.model_version_recorded:
        risk_score += 0.05
        violations.append("model_version_missing")

    # data_sources incomplete → provenance gap
    if not decision.data_sources_complete:
        risk_score += 0.05
        violations.append("data_sources_incomplete")

    # We cap the risk score between 0.0 and 1.0 for safety.
    risk_score = max(0.0, min(1.0, risk_score))

    # Now we map the numeric risk score to a textual risk level band.
    # These thresholds come directly from the document.
    if 0.00 <= risk_score <= 0.20:
        risk_level = "GREEN"   # compliant
    elif 0.21 <= risk_score <= 0.40:
        risk_level = "AMBER"   # review recommended
    elif 0.41 <= risk_score <= 0.65:
        risk_level = "HIGH"    # human review required
    else:  # 0.66 - 1.00
        risk_level = "CRITICAL"  # block / escalate

    # Next, we decide which action GovGuard should recommend.
    # We use the four actions from Section 5.3.
    if risk_level == "GREEN":
        action = "ALLOW"
    elif risk_level == "AMBER":
        action = "LOG_FOR_AUDIT"
    elif risk_level == "HIGH":
        action = "REQUIRE_HUMAN_REVIEW"
    else:
        action = "BLOCK_ACTION"

    # Finally, we return a dictionary that matches the expected structure
    # from Section 12.3 for the first prototype.
    return {
        "risk_score": round(risk_score, 2),  # round to two decimal places for readability
        "risk_level": risk_level,
        "action": action,
        "violations": violations,
        "framework": "uk_ai_playbook",
    }